name: Gaston Serralta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-22173827-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#786f5e'
    - '#0e0c0d'
    - '#baa894'
    - '#67372c'
  brandStrength: 0.5154874087311327
  lightness: 0.4394373616669327
  saturation: 0.7130301664583385
  rhythmicContrast: 0.2823279465083033
purpose: []
